stylesheets:
  application:
    - shared
    - application

javascripts:
  modernizr:
    - modernizr.min
    - modernizr-nav
  application:
    - augmented.min
    - dispatcher
    - i18n
    - application
